start = blocks:blocks {return blocks.reduce((prev, current) => { 
	if (+current.name == 1) { prev.push([current]); return prev;}
prev[prev.length -1].push(current); return prev;
}, [])}

blocks = block*

block = simpleblock / complexblock

simpleblock = "{" name:$[^:]+ ":" content:text "}" whitespace { return { name , content}} 
complexblock = "{" name:$[^:]+ ":" content:simpleblock* "}" whitespace { return { name , content}}
whitespace = [ \t\n\r]*
text = chars:$[^{}]+
newLine = '\n' / '\r\n'?